spring.application.name=DocuMindAI
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.datasource.url=jdbc:postgresql://localhost:5432/documind_ai
spring.datasource.username=postgres
spring.datasource.password=anshuman

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
